test ghc-10.0 in CI
haskell-ci is deprecated and I don't want to bother rewriting the CI
script right now, so I am patching the file by hand and hoping for the
best

diff --git a/.github/workflows/haskell-ci.yml b/.github/workflows/haskell-ci.yml
--- a/.github/workflows/haskell-ci.yml
+++ b/.github/workflows/haskell-ci.yml
@@ -1,17 +1,8 @@
-# This GitHub workflow config has been generated by a script via
+# This GitHub workflow config was originally generated by
 #
 #   haskell-ci 'github' 'cabal.project'
 #
-# To regenerate the script (for example after adjusting tested-with) run
-#
-#   haskell-ci regenerate
-#
-# For more information, see https://github.com/haskell-CI/haskell-ci
-#
-# version: 0.19.20260104
-#
-# REGENDATA ("0.19.20260104",["github","cabal.project"])
-#
+# But haskell-ci is now deprecated, so it is now modified by hand.
 name: Haskell-CI
 on:
   - push
@@ -29,76 +20,81 @@ jobs:
     strategy:
       matrix:
         include:
-          - compiler: ghc-9.14.1
+          - compiler: ghc-10.0.0.20260917
             compilerKind: ghc
-            compilerVersion: 9.14.1
+            compilerVersion: 10.0.0.20260917
             setup-method: ghcup
             allow-failure: false
-          - compiler: ghc-9.12.2
-            compilerKind: ghc
-            compilerVersion: 9.12.2
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-9.10.3
-            compilerKind: ghc
-            compilerVersion: 9.10.3
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-9.8.4
-            compilerKind: ghc
-            compilerVersion: 9.8.4
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-9.6.6
-            compilerKind: ghc
-            compilerVersion: 9.6.6
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-9.4.8
-            compilerKind: ghc
-            compilerVersion: 9.4.8
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-9.2.8
-            compilerKind: ghc
-            compilerVersion: 9.2.8
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-9.0.2
-            compilerKind: ghc
-            compilerVersion: 9.0.2
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-8.10.7
-            compilerKind: ghc
-            compilerVersion: 8.10.7
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-8.8.4
-            compilerKind: ghc
-            compilerVersion: 8.8.4
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-8.6.5
-            compilerKind: ghc
-            compilerVersion: 8.6.5
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-8.4.4
-            compilerKind: ghc
-            compilerVersion: 8.4.4
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-8.2.2
-            compilerKind: ghc
-            compilerVersion: 8.2.2
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-8.0.2
-            compilerKind: ghc
-            compilerVersion: 8.0.2
-            setup-method: ghcup
-            allow-failure: false
+          #- compiler: ghc-9.14.1
+          #  compilerKind: ghc
+          #  compilerVersion: 9.14.1
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-9.12.4
+          #  compilerKind: ghc
+          #  compilerVersion: 9.12.4
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-9.10.3
+          #  compilerKind: ghc
+          #  compilerVersion: 9.10.3
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-9.8.4
+          #  compilerKind: ghc
+          #  compilerVersion: 9.8.4
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-9.6.6
+          #  compilerKind: ghc
+          #  compilerVersion: 9.6.6
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-9.4.8
+          #  compilerKind: ghc
+          #  compilerVersion: 9.4.8
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-9.2.8
+          #  compilerKind: ghc
+          #  compilerVersion: 9.2.8
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-9.0.2
+          #  compilerKind: ghc
+          #  compilerVersion: 9.0.2
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-8.10.7
+          #  compilerKind: ghc
+          #  compilerVersion: 8.10.7
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-8.8.4
+          #  compilerKind: ghc
+          #  compilerVersion: 8.8.4
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-8.6.5
+          #  compilerKind: ghc
+          #  compilerVersion: 8.6.5
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-8.4.4
+          #  compilerKind: ghc
+          #  compilerVersion: 8.4.4
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-8.2.2
+          #  compilerKind: ghc
+          #  compilerVersion: 8.2.2
+          #  setup-method: ghcup
+          #  allow-failure: false
+          #- compiler: ghc-8.0.2
+          #  compilerKind: ghc
+          #  compilerVersion: 8.0.2
+          #  setup-method: ghcup
+          #  allow-failure: false
       fail-fast: false
     steps:
       - name: apt-get install
@@ -110,10 +106,13 @@ jobs:
           mkdir -p "$HOME/.ghcup/bin"
           curl -sL https://downloads.haskell.org/ghcup/0.1.50.1/x86_64-linux-ghcup-0.1.50.1 > "$HOME/.ghcup/bin/ghcup"
           chmod a+x "$HOME/.ghcup/bin/ghcup"
+          "$HOME/.ghcup/bin/ghcup" upgrade
+          "$HOME/.ghcup/bin/ghcup" config add-release-channel prereleases
+          "$HOME/.ghcup/bin/ghcup" list
       - name: Install cabal-install
         run: |
-          "$HOME/.ghcup/bin/ghcup" install cabal 3.16.0.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
-          echo "CABAL=$HOME/.ghcup/bin/cabal-3.16.0.0 -vnormal+nowrap" >> "$GITHUB_ENV"
+          "$HOME/.ghcup/bin/ghcup" install cabal 3.18.1.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
+          echo "CABAL=$HOME/.ghcup/bin/cabal-3.18.1.0 -vnormal+nowrap" >> "$GITHUB_ENV"
       - name: Install GHC (GHCup)
         if: matrix.setup-method == 'ghcup'
         run: |
